#  server:
#    port: ${PORT:0}
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  # MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # UPLOAD FILE SIZE
  servlet:
    multipart:
      max-file-size: 10MB
  # RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "menu"
    description: "Menu Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      cameriere:
        menu: DEBUG
