#  server:
#    port: ${PORT:0}
server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    username: root
    password: root
  jpa:
    show-sql: true
  # UPLOAD FILE SIZE
  servlet:
    multipart:
      max-file-size: 10MB
  # RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true