#  server:
#    port: ${PORT:0}
server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# # MYSQL
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/menu_db?serverTimezone=America/Sao_Paulo
#     username: root
#     password: root
#   jpa:
#     hibernate:
#       ddl-auto: create-drop

# H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
  # UPLOAD FILE SIZE
  servlet:
    multipart:
      max-file-size: 10MB
  # RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"