server:
  port: 8082

spring:
  # H2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
  # RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: order
